dist: bionic
language: csharp
mono: none
dotnet: 3.1.101
jobs:
  - name: c,cpp
    install: sudo apt install clang-8
    script: make -j2 test-c test-cpp
  - name: cs,java
    mono: latest
    script: make -j2 test-cs test-java
  - name: js,py,error
    script: make -j2 test-js test-py test-error
