language: csharp
dist: bionic
mono: none
dotnet: 3.1.101
jobs:
  - name: cpp
    install:
      - lsb_release -a
      - lscpu
      - sudo apt install libstdc++-8-dev
    script: make -j2 test-cpp
  - name: py
    install: python3 --version
    script: make -j2 test-py
  - name: py 3.8
    python: 3.8
    install: python3 --version
    script: make -j2 test-py
