dist: bionic
language: csharp
mono: none
dotnet: 3.1.101
jobs:
  - name: c
    script: make -j2 test-c test-error
  - name: cs
    mono: latest
    script: make -j2 test-cs
  - name: java,js
    script: make -j2 test-java test-js
