dist: bionic
language: csharp
mono: none
dotnet: 3.1.101
jobs:
  - name: c, java
    script: make -j2 test-c test-java
  - name: cs
    mono: latest
    script: make -j2 test-cs
  - name: js, error
    script: make -j2 test-js test-error
