language: csharp
mono: none
dotnet: 3.1.101
jobs:
  - name: cpp
    install:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - sudo apt-get update
      - sudo apt-get install libstdc++-9-dev
    script: make -j2 test-cpp
  - name: cpp2
    install:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - sudo apt-get update
      - sudo apt-get install g++-9
    script: make -j2 test-cpp
  - name: py
    install:
      - sudo add-apt-repository -y ppa:deadsnakes/ppa
      - sudo apt update
      - sudo apt install python3.8
    script: make -j2 test-py PYTHON=python3.8
