dist: bionic
language: csharp
mono: none
dotnet: 3.1.101
jobs:
  - name: cpp
    install: sudo apt install clang-9
    script: make -j2 test-cpp
  - name: cs
    mono: latest
    script: make -j2 test-cs
  - name: py
    install:
      - sudo apt install python3-pip
      - pip3 install --user pyfma
    script: make -j2 test-py
