language: csharp
mono: none
dotnet: 3.1.201
jobs:
  - name: c, js
    script: make -j2 test-c test-js
  - name: cpp, py
    install:
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo add-apt-repository -y ppa:deadsnakes/ppa
      - sudo apt update
      - sudo apt install libstdc++-9-dev python3.8
    script: make -j2 test-cpp test-py PYTHON=python3.8
  - name: cs
    mono: latest
    script: make -j2 test-cs
  - name: java
    script: make -j2 test-java
  - name: cl, error
    script: make -j2 test-cl test-error
