language: csharp
mono: none
dotnet: 3.1.201
jobs:
  - name: swift
    install:
      - wget https://swift.org/builds/swift-5.2.3-release/ubuntu1604/swift-5.2.3-RELEASE/swift-5.2.3-RELEASE-ubuntu16.04.tar.gz
      - tar xf swift-5.2.3-RELEASE-ubuntu16.04.tar.gz
    script: make -j2 test-swift SWIFTC=~/swift-5.2.3-RELEASE-ubuntu16.04/usr/bin/swiftc
