language: csharp
mono: none
dotnet: 3.1.201
jobs:
  - name: c, js, cl
    script: make -j2 test-c test-js test-cl
  - name: cpp, py
    install:
      - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - sudo add-apt-repository -y ppa:deadsnakes/ppa
      - sudo apt update
      - sudo apt install libstdc++-9-dev python3.8
    script: make -j2 test-cpp test-py PYTHON=python3.8
  - name: cs, java, error
    mono: latest
    script: make -j2 test-cs test-java test-error
