language: csharp
mono: none
dotnet: 3.1.101
jobs:
  - name: py
    install:
      - sudo add-apt-repository -y ppa:deadsnakes/ppa
      - sudo apt update
      - sudo apt install python3.8
    script: make -j2 test-py PYTHON=python3.8
