dist: bionic
language: csharp
mono: none
dotnet: 3.1.101
jobs:
  - name: cpp
    script: make -j2 test-cpp
  - name: cs
    script: make -j2 test-cs
  - name: py
    install: pip install --user pyfma
    script: make -j2 test-py
